name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Debug and Release
    runs-on: windows-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M%S')"

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Debug
        run: |
          msbuild re4_tweaks.sln /p:Configuration=Debug /p:PostBuildEventUseInBuild=false

      - name: Build Release
        run: |
          msbuild re4_tweaks.sln /p:Configuration=Release /p:PostBuildEventUseInBuild=false

      - name: Create default configuration file
        shell: bash
        run: |
          awk 'NR > 1 { \
            if (NR == 2) { print substr($0, 37); } \
            else { gsub(")\"\"\"\";", "", $0); print $0 } \
          }' settings/settings_string.h > dinput8.ini

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: |
            Debug/dinput8.dll
            Release/dinput8.dll
            dinput8.ini
          name: re4_tweaks_${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}
